name 'liferay'
maintainer 'Max Goltzsche'
maintainer_email 'max.goltzsche@gmail.com'
license 'Apache 2.0'
description 'Installs and configures Liferay'
version '0.1.0'

depends 'apt'
depends 'unzip'
depends 'imagemagick'
depends 'database'
depends 'postgresql'
